# ###################################################################
# (c) Kancelaria Prezesa Rady Ministrów 2012-2015                   #
# Treść licencji w pliku 'LICENCE'                                  #
#                                                                   #
# (c) Chancellery of the Prime Minister 2012-2015                   #
# Licence terms can be found in the file 'LICENCE'                  #
#                                                                   #
# Authors: Karol Podemski, Kaja Retkiewicz-Wijtiwiak                #
# ###################################################################
# Functions make_model and load_model
# ###################################################################


# ###################################################################
# The to_r function attaches the .R extension if the model file
# was specified without any extension
# ###################################################################
# Input 
#   strn - the name of model file (string)
# Output
#   A string with r extension if model file was specified without
#                                       any extension
# ###################################################################
to_r <- function(strn)
{
    if (length(grep(pattern="(?i)\\.model\\.R$", x = strn, perl = TRUE))) {
        return(strn)
    } else {
        if (length(grep(pattern="(?i)\\.R$", x = strn, perl = TRUE))) {
            strn <- gsub(pattern="(?i)\\.R$", replacement = '',
                     x = strn, perl = TRUE)
            warning(paste('Since the release of gEcon 0.7.0 model files are generated',
                          'with the extension .model.R. It is recommended to use raw name of file or',
                          'name of file with the extension .model.R'))
        }
        return(paste(strn, '.model.R', sep = ""))
    }
}

# ###################################################################
# The to_gcn function attaches .gcn extension if the model file
# was specified without any extension
# ###################################################################
# Input 
#   strn - a name of model file (string)
# Output
#   A string with .gcn extension if model file was specified without
#                                       any extension
# ###################################################################
to_gcn <- function(strn)
{
    if (length(grep(pattern="(?i)\\.gcn$", x= strn, perl = TRUE))) {
        return(strn)
    } else {
        return(paste(strn, '.gcn', sep = ""))
    }
}

# ###################################################################
# The undo_gcn function removes the .gcn extension from sting
# ###################################################################
# Input 
#   strn - name of model file
# Output
#   string without .gcn extension
# ###################################################################
undo_gcn <- function(strn)
{
    strn <- gsub(pattern="(?i)\\.gcn$", replacement='',
                 x= strn, perl = TRUE)
    return(strn)
}

# ###################################################################
# The make_model function calls dynamic library, parses model file,
# generates R output and loads it into gecon_model class object
# ###################################################################
# Input 
#   model_file - a name of model file (.gcn file)
# Output
#   generates gecon_model class object
# ###################################################################
make_model <- function(model_file)
{
    if (is.null(model_file) | model_file == '')
    {
        stop('Name of model has to be passed as a nonempty string')
    }

    # try to get absolute path
    res <- tryCatch(expr = {
            model_file <- normalizePath(model_file, 
                                        winslash = "/", 
                                        mustWork = TRUE)
            TRUE
        },
        error = function(e) FALSE
    )
    
    # if file does not exist, print error
    if (!res) {
        stop('The specified gcn. file does NOT exist in the chosen directory')
    }
    
    # calling C++ routines to obtain file with model equations
    comman <- .Call("parse_from_R", model_file)
    
    # removing extension
    str <- undo_gcn(model_file)
    
    # loading model from R file
    return(load_model(str))
}

# ###################################################################
# The load_model function loads already generated R file with 
# model and creates model class object
# ###################################################################
# Input 
#   model_file - name of model file (.R file already generated by tool).
# Output
#   generates model class object
# ###################################################################
load_model <- function(model_file)
{
    if (is.null(model_file) | model_file == '')
    {
        stop('Name of model has to be passed as a nonempty string')
    }

    # adding extension if it is missing
    model_file <- to_r(model_file)    
    
    # sourcing model
    return(eval(parse(model_file)))
}

